// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRnb-GN4EIQJQyXR4oLMSLgUUVZ-7dfLk',
    appId: '1:1091559223871:web:966f20493bc2b05eccfe8a',
    messagingSenderId: '1091559223871',
    projectId: 'chat-f535d',
    authDomain: 'chat-f535d.firebaseapp.com',
    storageBucket: 'chat-f535d.appspot.com',
    measurementId: 'G-1090H5N6QP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGWhxYkMF152kp0lLD79G-J_xQI6rxI5k',
    appId: '1:1091559223871:android:f01434aa508794e2ccfe8a',
    messagingSenderId: '1091559223871',
    projectId: 'chat-f535d',
    storageBucket: 'chat-f535d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEk6-kqHSuEcaUGblZTD3-rO1ffImpSeQ',
    appId: '1:1091559223871:ios:75500025ec4ee839ccfe8a',
    messagingSenderId: '1091559223871',
    projectId: 'chat-f535d',
    storageBucket: 'chat-f535d.appspot.com',
    iosClientId: '1091559223871-i2vs3e2dig6c3p4v2gnp997rvkc5ul76.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEk6-kqHSuEcaUGblZTD3-rO1ffImpSeQ',
    appId: '1:1091559223871:ios:75500025ec4ee839ccfe8a',
    messagingSenderId: '1091559223871',
    projectId: 'chat-f535d',
    storageBucket: 'chat-f535d.appspot.com',
    iosClientId: '1091559223871-i2vs3e2dig6c3p4v2gnp997rvkc5ul76.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
